require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PowerSuppliesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PowerSupply. As you add validations to PowerSupply, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PowerSuppliesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all power_supplies as @power_supplies" do
      power_supply = PowerSupply.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:power_supplies)).to eq([power_supply])
    end
  end

  describe "GET #show" do
    it "assigns the requested power_supply as @power_supply" do
      power_supply = PowerSupply.create! valid_attributes
      get :show, params: {id: power_supply.to_param}, session: valid_session
      expect(assigns(:power_supply)).to eq(power_supply)
    end
  end

  describe "GET #new" do
    it "assigns a new power_supply as @power_supply" do
      get :new, params: {}, session: valid_session
      expect(assigns(:power_supply)).to be_a_new(PowerSupply)
    end
  end

  describe "GET #edit" do
    it "assigns the requested power_supply as @power_supply" do
      power_supply = PowerSupply.create! valid_attributes
      get :edit, params: {id: power_supply.to_param}, session: valid_session
      expect(assigns(:power_supply)).to eq(power_supply)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PowerSupply" do
        expect {
          post :create, params: {power_supply: valid_attributes}, session: valid_session
        }.to change(PowerSupply, :count).by(1)
      end

      it "assigns a newly created power_supply as @power_supply" do
        post :create, params: {power_supply: valid_attributes}, session: valid_session
        expect(assigns(:power_supply)).to be_a(PowerSupply)
        expect(assigns(:power_supply)).to be_persisted
      end

      it "redirects to the created power_supply" do
        post :create, params: {power_supply: valid_attributes}, session: valid_session
        expect(response).to redirect_to(PowerSupply.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved power_supply as @power_supply" do
        post :create, params: {power_supply: invalid_attributes}, session: valid_session
        expect(assigns(:power_supply)).to be_a_new(PowerSupply)
      end

      it "re-renders the 'new' template" do
        post :create, params: {power_supply: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested power_supply" do
        power_supply = PowerSupply.create! valid_attributes
        put :update, params: {id: power_supply.to_param, power_supply: new_attributes}, session: valid_session
        power_supply.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested power_supply as @power_supply" do
        power_supply = PowerSupply.create! valid_attributes
        put :update, params: {id: power_supply.to_param, power_supply: valid_attributes}, session: valid_session
        expect(assigns(:power_supply)).to eq(power_supply)
      end

      it "redirects to the power_supply" do
        power_supply = PowerSupply.create! valid_attributes
        put :update, params: {id: power_supply.to_param, power_supply: valid_attributes}, session: valid_session
        expect(response).to redirect_to(power_supply)
      end
    end

    context "with invalid params" do
      it "assigns the power_supply as @power_supply" do
        power_supply = PowerSupply.create! valid_attributes
        put :update, params: {id: power_supply.to_param, power_supply: invalid_attributes}, session: valid_session
        expect(assigns(:power_supply)).to eq(power_supply)
      end

      it "re-renders the 'edit' template" do
        power_supply = PowerSupply.create! valid_attributes
        put :update, params: {id: power_supply.to_param, power_supply: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested power_supply" do
      power_supply = PowerSupply.create! valid_attributes
      expect {
        delete :destroy, params: {id: power_supply.to_param}, session: valid_session
      }.to change(PowerSupply, :count).by(-1)
    end

    it "redirects to the power_supplies list" do
      power_supply = PowerSupply.create! valid_attributes
      delete :destroy, params: {id: power_supply.to_param}, session: valid_session
      expect(response).to redirect_to(power_supplies_url)
    end
  end

end
